-- H2 Database
drop table if exists member cascade;
create table member
(
    id bigint generated by default as identity,
    name varchar(255),
    primary key (id)
);

-- MariaDB
CREATE TABLE member (
                        id BIGINT AUTO_INCREMENT,
                        name VARCHAR(255),
                        PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;